"""In-memory engineering report and data-export workflow."""

from __future__ import annotations

import io
import logging
import math
from collections.abc import Callable
from datetime import UTC, datetime
from typing import NotRequired, TypedDict

import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st

from src.calculations import ideal_comparison, parameter_sweep
from src.course import AppMode
from src.models import IdealComparison, JetInputs, SimulationResult
from src.reporting import (
    ReportError,
    ReportFigure,
    export_case_csv,
    export_case_json,
    export_case_pdf,
    export_printable_html,
    reportlab_available,
    safe_export_filename,
)
from src.utils import percentage_difference
from src.validation import hand_calculation_trace
from src.visualizations import (
    ASSUMPTIONS,
    MODEL_LABELS,
    input_snapshot,
    render_brand_bar,
    render_disclaimer,
    render_engineering_schematic,
    render_force_cards,
    render_page_intro,
    render_sidebar_controls,
    result_snapshot,
    simulate_safely,
)

LOGGER = logging.getLogger(__name__)


class _ReportOptions(TypedDict):
    """Keyword options shared by every report serializer."""

    metadata: dict[str, str]
    assumptions: list[str]
    hand_calculation: dict[str, object]
    ideal_comparison: IdealComparison | None
    parametric_data: pd.DataFrame | None
    conclusion: str | None
    generated_at: datetime
    discussion: NotRequired[tuple[str, ...]]


def _study(inputs: JetInputs, variable: str, points: int) -> pd.DataFrame:
    if variable == "velocity":
        stop = max(20.0, min(50.0, inputs.velocity * 1.75))
        return parameter_sweep(inputs, variable, start=0.0, stop=stop, points=points)
    stop = max(0.05, min(0.1, inputs.diameter * 2.0))
    return parameter_sweep(inputs, variable, start=0.005, stop=stop, points=points)


def _combined_study_table(studies: dict[str, pd.DataFrame]) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    for variable, frame in studies.items():
        normalized = frame.rename(columns={variable: "input_value"}).copy()
        normalized.insert(0, "study_variable", variable)
        normalized.insert(2, "input_unit", "m/s" if variable == "velocity" else "m")
        frames.append(normalized)
    return pd.concat(frames, ignore_index=True)


def _study_figure(frame: pd.DataFrame, variable: str, model_label: str) -> ReportFigure:
    """Create one print-ready PNG from the exact exported study data."""

    x_label = "Inlet jet velocity, V (m/s)" if variable == "velocity" else "Jet diameter, d (m)"
    title = "Force versus inlet velocity" if variable == "velocity" else "Force versus jet diameter"
    figure, axis = plt.subplots(figsize=(8.8, 4.8), dpi=170, constrained_layout=True)
    axis.plot(
        frame[variable], frame["Fx_N"], label="Fx - horizontal", color="#0891b2", linewidth=2.2
    )
    axis.plot(frame[variable], frame["Fy_N"], label="Fy - vertical", color="#d97706", linewidth=2.2)
    axis.plot(
        frame[variable], frame["FR_N"], label="FR - resultant", color="#e11d48", linewidth=2.6
    )
    axis.axhline(0.0, color="#64748b", linewidth=0.8)
    axis.set_title(f"{title}\n{model_label}", loc="left", fontweight="bold")
    axis.set_xlabel(x_label)
    axis.set_ylabel("Force exerted on plate (N)")
    axis.grid(True, color="#cbd5e1", alpha=0.6, linewidth=0.6)
    axis.legend(frameon=False, ncol=3, loc="upper left")
    buffer = io.BytesIO()
    figure.savefig(buffer, format="png", dpi=170, facecolor="white")
    plt.close(figure)
    return ReportFigure(
        title=title,
        image_bytes=buffer.getvalue(),
        caption=(
            f"Signed reaction components and resultant force versus {x_label.lower()}. "
            "The data are generated by the same control-volume model as the selected case."
        ),
        alt_text=f"Line chart of Fx, Fy, and resultant force against {x_label.lower()}.",
    )


def _report_options(
    inputs: JetInputs,
    result: SimulationResult,
    metadata: dict[str, str],
    discussion_text: str,
    conclusion: str,
    include_studies: bool,
    study_points: int,
    generated_at: datetime,
    *,
    course_mode: bool,
) -> tuple[_ReportOptions, tuple[ReportFigure, ...]]:
    res = result_snapshot(result, inputs)
    hand = hand_calculation_trace(result)

    def comparison(component: str, hand_value: float, simulator_value: float) -> dict[str, object]:
        absolute = abs(hand_value - simulator_value)
        percent = percentage_difference(hand_value, simulator_value)
        percentage: float | str = "not applicable" if math.isnan(percent) else percent
        return {
            "component": component,
            "hand_calculation_n": hand_value,
            "simulator_n": simulator_value,
            "absolute_difference_n": absolute,
            "percentage_difference": percentage,
        }

    component_comparisons = (
        comparison("fx", hand.fx_n, res["fx"]),
        comparison("fy", hand.fy_n, res["fy"]),
        comparison("fr", hand.resultant_force_n, res["fr"]),
    )
    flat_comparison = {
        f"{item['component']}_{field}": value
        for item in component_comparisons
        for field, value in item.items()
        if field != "component"
    }
    hand_calculation: dict[str, object] = {
        "area_equation": "A = pi d^2 / 4",
        "area_m2": hand.area_m2,
        "flow_equation": "Q = A V",
        "flow_rate_m3_s": hand.flow_rate_m3_s,
        "mass_flow_equation": "mdot = rho Q",
        "mass_flow_rate_kg_s": hand.mass_flow_rate_kg_s,
        "outlet_momentum_flux_x_n": hand.outlet_momentum_flux_x_n,
        "outlet_momentum_flux_y_n": hand.outlet_momentum_flux_y_n,
        "force_equation": "F_plate = mdot V_in - sum(mdot_j V_out,j)",
        **flat_comparison,
        "comparison_note": (
            "The hand calculation and simulator use the same documented analytical model; "
            "agreement within floating-point rounding is expected and is not experimental validation."
        ),
    }

    study_table: pd.DataFrame | None = None
    figures: tuple[ReportFigure, ...] = ()
    if include_studies:
        studies = {
            "velocity": _study(inputs, "velocity", study_points),
            "diameter": _study(inputs, "diameter", study_points),
        }
        study_table = _combined_study_table(studies)
        figures = tuple(
            _study_figure(frame, variable, MODEL_LABELS[inputs.model.value])
            for variable, frame in studies.items()
        )

    discussion = (
        tuple(line.strip() for line in discussion_text.splitlines() if line.strip()) or None
    )
    options: _ReportOptions = {
        "metadata": metadata,
        "assumptions": [
            f"{title}: {explanation}"
            for title, explanation in (ASSUMPTIONS[:8] if course_mode else ASSUMPTIONS)
        ],
        "hand_calculation": hand_calculation,
        "ideal_comparison": None if course_mode else ideal_comparison(inputs),
        "parametric_data": study_table,
        "conclusion": conclusion.strip() or None,
        "generated_at": generated_at,
    }
    if discussion is not None:
        options["discussion"] = discussion
    return options, figures


def _fingerprint(
    inputs: JetInputs,
    metadata: dict[str, str],
    include_studies: bool,
    study_points: int,
    discussion: str,
    conclusion: str,
) -> str:
    return repr(
        (
            inputs,
            tuple(sorted(metadata.items())),
            include_studies,
            study_points,
            discussion,
            conclusion,
        )
    )


mode = AppMode(st.session_state.get("jf_mode", AppMode.COURSE.value))
course_mode = mode is AppMode.COURSE
inputs, unit_system = render_sidebar_controls()
result = simulate_safely(inputs)
if result is None:
    st.stop()

render_brand_bar()
render_page_intro(
    "Report-ready deliverables",
    "Report and Export",
    "Generate reviewable CSV, JSON, printable HTML, and PDF artifacts in memory without storing visitor reports on the server.",
)
render_disclaimer()

st.markdown("## Current-case preview")
render_force_cards(result, inputs, unit_system, course_mode=course_mode)
with st.expander("Preview control-volume schematic", expanded=False):
    render_engineering_schematic(inputs, result, show_controls=False, height=455)

st.markdown("## Report identity")
identity_columns = st.columns(2)
with identity_columns[0]:
    report_title = st.text_input(
        "Report title",
        value="Interactive Numerical Modeling and Analysis of a Water Jet Striking a Flat or Curved Plate",
    )
    student_name = st.text_input("Student name", placeholder="Complete before submission")
    student_id = st.text_input("Student ID", placeholder="Complete before submission")
with identity_columns[1]:
    course = st.text_input("Course", value="MEC350 Fluid Mechanics")
    instructor = st.text_input("Instructor / section", placeholder="Complete before submission")
    institution = st.text_input("Institution", placeholder="Complete before submission")

st.markdown("## Study and interpretation")
with st.container(horizontal=True, gap="medium"):
    include_studies = st.toggle(
        "Include velocity and diameter charts",
        value=True,
        help="Adds both Course Mode studies, their exact data table, and two print-ready figures.",
    )
    study_points = st.number_input(
        "Points per study",
        min_value=21,
        max_value=201,
        value=61,
        disabled=not include_studies,
    )

default_discussion = (
    "Interpret component signs using positive x along the inlet jet and positive y upward.\n"
    "Explain the force trend through mass flow and the change in momentum vectors.\n"
    "State that the schematic is illustrative and the analytical agreement is not experimental validation."
)
if not course_mode:
    default_discussion += "\nState that k is a prescribed outlet-speed assumption, not a CFD or Reynolds-number prediction."
discussion = st.text_area(
    "Discussion points (one paragraph per line)",
    value=default_discussion,
    height=145,
)
conclusion = st.text_area(
    "Case-specific conclusion",
    placeholder="Summarize the principal force result and verified trend. Review before submission.",
    height=95,
)

metadata = {
    "title": report_title.strip() or "Water Jet Impact Analysis",
    "subtitle": "JetForce Studio - Water Jet Impact Engineering Simulator",
    "course": course.strip() or "MEC350 Fluid Mechanics",
    "interface_mode": mode.value,
    "student_name": student_name.strip() or "[Complete before submission]",
    "student_id": student_id.strip() or "[Complete before submission]",
    "instructor_section": instructor.strip() or "[Complete before submission]",
    "institution": institution.strip() or "[Complete before submission]",
    "model": MODEL_LABELS[input_snapshot(inputs)["model"]],
    "review_status": "Draft - student review required",
}
current_fingerprint = _fingerprint(
    inputs,
    metadata,
    include_studies,
    int(study_points),
    discussion,
    conclusion,
)

existing_package = st.session_state.get("jf_report_package")
generate_label = (
    "Retry Report Generation"
    if existing_package and existing_package.get("errors")
    else "Generate Export Package"
)
if st.button(
    generate_label,
    type="primary",
    icon=":material/settings:",
    width="stretch",
):
    generated_at = datetime.now(UTC)
    artifacts: dict[str, bytes] = {}
    errors: list[str] = []
    try:
        options, figures = _report_options(
            inputs,
            result,
            metadata,
            discussion,
            conclusion,
            include_studies,
            int(study_points),
            generated_at,
            course_mode=course_mode,
        )
        exporters: tuple[tuple[str, Callable[[], bytes]], ...] = (
            ("csv", lambda: export_case_csv(inputs, result, **options)),
            ("json", lambda: export_case_json(inputs, result, **options)),
            (
                "html",
                lambda: export_printable_html(inputs, result, figures=figures, **options),
            ),
        )
        for extension, exporter in exporters:
            try:
                artifacts[extension] = exporter()
            except ReportError as exc:
                errors.append(f"{extension.upper()}: {exc}")
        if reportlab_available():
            try:
                artifacts["pdf"] = export_case_pdf(inputs, result, figures=figures, **options)
            except ReportError as exc:
                errors.append(f"PDF: {exc}")
        else:
            errors.append("PDF: ReportLab is unavailable; use printable HTML as the fallback.")
    except (ReportError, ValueError) as exc:
        errors.append(str(exc))
    except Exception:
        LOGGER.exception("Unexpected report-generation failure")
        errors.append(
            "An unexpected report-generation problem occurred. Verify dependencies and select Retry Report Generation."
        )

    st.session_state.jf_report_package = {
        "artifacts": artifacts,
        "errors": errors,
        "fingerprint": current_fingerprint,
        "generated_at": generated_at,
    }

package = st.session_state.get("jf_report_package")
if package:
    package_is_current = package["fingerprint"] == current_fingerprint
    if not package_is_current:
        st.warning(
            "The case or report fields changed after this package was generated. Downloads are hidden to prevent a stale export; generate the package again.",
            icon=":material/warning:",
        )
    artifacts = package["artifacts"]
    if artifacts and package_is_current:
        generated_at = package["generated_at"]
        st.success(
            f"Prepared {len(artifacts)} in-memory artifacts. No visitor report was written to permanent storage.",
            icon=":material/check_circle:",
        )
        stem = "jetforce_course_case" if course_mode else "jetforce_advanced_case"
        labels = {
            "csv": ("Case CSV", "text/csv", ":material/table_view:"),
            "json": ("Structured JSON", "application/json", ":material/data_object:"),
            "html": ("Printable HTML", "text/html", ":material/language:"),
            "pdf": ("Engineering PDF", "application/pdf", ":material/picture_as_pdf:"),
        }
        with st.container(horizontal=True, gap="small"):
            for extension in ("csv", "json", "html", "pdf"):
                if extension in artifacts:
                    label, mime, icon = labels[extension]
                    st.download_button(
                        label,
                        data=artifacts[extension],
                        file_name=safe_export_filename(stem, extension, generated_at=generated_at),
                        mime=mime,
                        icon=icon,
                        width="stretch",
                    )
        if "html" in artifacts:
            with st.expander("Preview printable HTML", expanded=False):
                st.iframe(
                    artifacts["html"].decode("utf-8"),
                    width="stretch",
                    height=720,
                    tab_index=0,
                )
    if package_is_current:
        for message in package.get("errors", []):
            st.error(
                f"One export could not be created: {message} Use Retry Report Generation after correcting the issue.",
                icon=":material/error:",
            )

st.info(
    "Every export is a draft. Verify inputs and units, complete student details, add only references you have personally checked, and write a case-specific discussion before submission.",
    icon=":material/edit_note:",
)
