"""Deterministic report exports for JetForce Studio.

The reporting layer deliberately consumes dataclasses or ordinary mappings and
does not recompute the governing physics.  It therefore remains a presentation
path over the authoritative values returned by :mod:`src.calculations`.
"""

from __future__ import annotations

import base64
import contextlib
import csv
import html
import importlib
import importlib.util
import io
import json
import math
import os
import re
import tempfile
import unicodedata
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass, is_dataclass
from datetime import UTC, datetime
from enum import Enum
from pathlib import Path
from typing import Any, cast

from .traceability import MODEL_REVISION, application_version, build_commit

SCHEMA_VERSION = "1.0"
DEFAULT_REPORT_TITLE = (
    "Interactive Numerical Modeling and Analysis of a Water Jet Striking a Flat or Curved Plate"
)
DEFAULT_REPORT_SUBTITLE = "JetForce Studio - Water Jet Impact Engineering Simulator"
DEFAULT_COURSE = "MEC350 Fluid Mechanics"
DISCLAIMER = (
    "This application uses a numerical control-volume momentum model. "
    "The flow visualization is illustrative and is not a full CFD simulation."
)
REVIEW_NOTE = (
    "Draft engineering report: the student must verify all inputs and results, "
    "complete the discussion, and add only references they have checked before submission."
)

DEFAULT_ASSUMPTIONS = (
    "Steady flow with no mass or momentum accumulation inside the control volume.",
    "Incompressible fluid with constant density.",
    "Uniform section-average velocity over each inlet and outlet jet.",
    "Exposed inlet and outlet free-jet surfaces are at atmospheric pressure, so gauge-pressure terms there are zero.",
    "The plate or vane is stationary and rigid.",
    "Gravity across the compact impact control volume and air resistance are neglected.",
    "The circular inlet jet retains its specified diameter before impact.",
    "The impact region is represented by a two-dimensional control volume.",
    "Non-ideal outlet loss is represented only by the prescribed velocity-retention coefficient k.",
    "The schematic and animation are engineering illustrations, not CFD solutions.",
)

GOVERNING_EQUATIONS = (
    "A = pi d^2 / 4",
    "Q = A V",
    "mdot = rho Q = rho A V",
    "F_plate = mdot V_in - sum(mdot_j V_out,j)",
    "Fx = mdot V_in,x - sum(mdot_j V_out,x,j)",
    "Fy = mdot V_in,y - sum(mdot_j V_out,y,j)",
    "FR = sqrt(Fx^2 + Fy^2)",
    "Re = rho V d / mu (diagnostic only)",
)

DEFAULT_DISCUSSION = (
    "Component signs follow positive x along the inlet jet and positive y upward. "
    "The reported vector is the force exerted by the fluid on the plate.",
    "Any non-ideal difference is controlled by the selected outlet-speed retention coefficient; "
    "it is not an experimental or CFD prediction.",
    "Interpret parameter trends through changes in mass flow and outlet momentum, and check the "
    "selected case against the documented limiting cases.",
)

DEFAULT_LIMITATIONS = (
    "The model does not solve spatial pressure, velocity, turbulence, or free-surface fields.",
    "Jet breakup, splashing, air entrainment, three-dimensional spreading, and nonuniform velocity profiles are not resolved.",
    "Transient loading, plate motion, torque, structural deformation, and fluid-structure interaction are outside scope.",
    "The velocity-retention coefficient is a user input unless supported by independently supplied measurements.",
    "Analytical equation checks are verification and are not experimental validation.",
)

_REPORT_IDENTITY_FIELDS = (
    ("student_name", "Student name"),
    ("student_id", "Student ID"),
    ("instructor_section", "Instructor / section"),
    ("institution", "Institution"),
)


class ReportError(RuntimeError):
    """Base class for readable report/export failures."""


class ReportDataError(ReportError, ValueError):
    """Raised when an export request contains no usable or unsupported data."""


class ReportDependencyError(ReportError):
    """Raised when an optional report dependency is unavailable."""


class ReportWriteError(ReportError, OSError):
    """Raised when generated bytes cannot be written to the requested path."""


@dataclass(frozen=True, slots=True)
class ReportFigure:
    """One verified raster image for a printable engineering report.

    ``image_bytes`` must contain PNG or JPEG data.  A caption is required so a
    figure remains understandable outside the live application.
    """

    title: str
    image_bytes: bytes
    caption: str
    alt_text: str = "Engineering result figure"
    mime_type: str = "image/png"

    def __post_init__(self) -> None:
        if not self.title.strip():
            raise ReportDataError("A report figure requires a non-empty title.")
        if not self.caption.strip():
            raise ReportDataError("A report figure requires a non-empty caption.")
        if not self.image_bytes:
            raise ReportDataError("A report figure cannot contain empty image data.")
        if self.mime_type not in {"image/png", "image/jpeg"}:
            raise ReportDataError("Report figures must be PNG or JPEG images.")


def reportlab_available() -> bool:
    """Return whether direct PDF generation is available in this environment."""

    return importlib.util.find_spec("reportlab") is not None


def _plain(value: Any) -> Any:
    """Convert supported Python/domain values to deterministic JSON-safe data."""

    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float):
        return value if math.isfinite(value) else "undefined"
    if isinstance(value, Enum):
        return _plain(value.value)
    if isinstance(value, (datetime,)):
        return value.isoformat()
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, Mapping):
        return {str(key): _plain(item) for key, item in value.items()}
    if hasattr(value, "item") and callable(value.item):
        try:
            scalar_value = value.item()
        except (TypeError, ValueError):
            scalar_value = value
        if scalar_value is not value:
            return _plain(scalar_value)
    if hasattr(value, "as_dict") and callable(value.as_dict):
        return _plain(value.as_dict())
    if hasattr(value, "to_dict") and callable(value.to_dict):
        try:
            mapping_value = value.to_dict()
        except TypeError:
            mapping_value = value
        if mapping_value is not value:
            return _plain(mapping_value)
    if is_dataclass(value) and not isinstance(value, type):
        return _plain(asdict(value))
    if isinstance(value, (set, frozenset)):
        converted = [_plain(item) for item in value]
        return sorted(
            converted,
            key=lambda item: json.dumps(item, ensure_ascii=True, sort_keys=True, default=str),
        )
    if isinstance(value, (list, tuple)):
        return [_plain(item) for item in value]
    raise ReportDataError(f"Unsupported report value type: {type(value).__name__}.")


def _mapping(value: Any, label: str) -> dict[str, Any]:
    plain = _plain(value)
    if not isinstance(plain, dict):
        raise ReportDataError(f"{label} must be a dataclass, model object, or mapping.")
    return plain


def _records(value: Any, label: str) -> list[dict[str, Any]]:
    """Convert a DataFrame-like object or sequence of mappings to records."""

    if value is None:
        return []
    if hasattr(value, "empty") and bool(value.empty):
        return []
    if hasattr(value, "to_dict") and callable(value.to_dict):
        try:
            candidate = value.to_dict(orient="records")
        except TypeError:
            candidate = value.to_dict()
    else:
        candidate = value
    plain = _plain(candidate)
    if isinstance(plain, dict):
        plain = [plain]
    if not isinstance(plain, list) or not all(isinstance(row, dict) for row in plain):
        raise ReportDataError(f"{label} must be a table or a sequence of row mappings.")
    return plain


def _generated_time(value: datetime | str | None) -> str:
    if value is None:
        value = datetime.now(UTC)
    if isinstance(value, str):
        candidate = value.strip()
        if not candidate:
            raise ReportDataError("Generation time cannot be blank.")
        try:
            value = datetime.fromisoformat(candidate.replace("Z", "+00:00"))
        except ValueError as exc:
            raise ReportDataError("Generation time must be a valid ISO 8601 timestamp.") from exc
    if value.tzinfo is None:
        value = value.replace(tzinfo=UTC)
    return value.astimezone(UTC).isoformat(timespec="seconds")


def build_report_payload(
    inputs: Any,
    result: Any | None = None,
    *,
    metadata: Mapping[str, Any] | None = None,
    assumptions: Sequence[str] | None = None,
    hand_calculation: Any | None = None,
    ideal_comparison: Any | None = None,
    parametric_data: Any | None = None,
    discussion: Sequence[str] | None = None,
    conclusion: str | None = None,
    limitations: Sequence[str] | None = None,
    generated_at: datetime | str | None = None,
) -> dict[str, Any]:
    """Build the canonical report payload without recalculating physics.

    ``inputs`` may be a ``JetInputs`` object, or it may be a simulation result
    when ``result`` is omitted.  The latter form uses ``result.inputs``.
    """

    if result is None and hasattr(inputs, "inputs"):
        result = inputs
        inputs = inputs.inputs
    if result is None:
        raise ReportDataError("A simulation result is required for a case export.")

    input_data = _mapping(inputs, "Inputs")
    result_data = _mapping(result, "Result")
    # SimulationResult.as_dict() intentionally contains input fields for easy
    # flat exports.  Avoid showing those fields twice in the structured report.
    for key in input_data:
        result_data.pop(key, None)
    if not input_data:
        raise ReportDataError("Inputs cannot be empty.")
    if not result_data:
        raise ReportDataError("Results cannot be empty.")
    if result_data.get("force_direction_defined") is False:
        result_data["force_angle_deg"] = "undefined"

    generated_timestamp = _generated_time(generated_at)
    report_meta: dict[str, Any] = {
        "title": DEFAULT_REPORT_TITLE,
        "subtitle": DEFAULT_REPORT_SUBTITLE,
        "course": DEFAULT_COURSE,
        "disclaimer": DISCLAIMER,
        "review_note": REVIEW_NOTE,
    }
    if metadata is not None:
        report_meta.update(_mapping(metadata, "Metadata"))
    # These reserved fields describe the code/model that generated the report.
    # Apply them after user metadata so a caller cannot accidentally spoof them.
    report_meta.update(
        {
            "application_version": application_version(),
            "model_revision": MODEL_REVISION,
            "build_commit": build_commit(),
            "generated_at": generated_timestamp,
        }
    )

    if report_meta.get("interface_mode") == "Course Mode":
        course_input_fields = {
            "density",
            "diameter",
            "velocity",
            "model",
            "fluid_preset",
            "unit_system",
        }
        if input_data.get("model") != "normal_flat_plate":
            course_input_fields.add("outlet_angle_deg")
        input_data = {key: value for key, value in input_data.items() if key in course_input_fields}
        course_result_fields = {
            "area_m2",
            "flow_rate_m3_s",
            "mass_flow_rate_kg_s",
            "inlet_velocity_x_m_s",
            "inlet_velocity_y_m_s",
            "equivalent_outlet_velocity_x_m_s",
            "equivalent_outlet_velocity_y_m_s",
            "outlet_momentum_flux_x_n",
            "outlet_momentum_flux_y_n",
            "fx_n",
            "fy_n",
            "resultant_force_n",
            "force_angle_deg",
            "force_direction_defined",
        }
        result_data = {
            key: value for key, value in result_data.items() if key in course_result_fields
        }

    selected_assumptions = list(DEFAULT_ASSUMPTIONS if assumptions is None else assumptions)
    selected_discussion = list(DEFAULT_DISCUSSION if discussion is None else discussion)
    selected_limitations = list(DEFAULT_LIMITATIONS if limitations is None else limitations)
    if not all(isinstance(item, str) and item.strip() for item in selected_assumptions):
        raise ReportDataError("Every assumption must be non-empty text.")
    if not all(isinstance(item, str) and item.strip() for item in selected_discussion):
        raise ReportDataError("Every discussion point must be non-empty text.")
    if not all(isinstance(item, str) and item.strip() for item in selected_limitations):
        raise ReportDataError("Every limitation must be non-empty text.")

    selected_equations = list(GOVERNING_EQUATIONS)
    if report_meta.get("interface_mode") == "Course Mode":
        selected_equations = [
            equation for equation in selected_equations if not equation.startswith("Re =")
        ]

    payload: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "report": _plain(report_meta),
        "case": {"inputs": input_data, "results": result_data},
        "assumptions": selected_assumptions,
        "governing_equations": selected_equations,
        "calculation_procedure": [
            "Calculate circular jet area from the specified diameter.",
            "Calculate volumetric and mass flow rates from the inlet speed.",
            "Construct the model-specific outlet velocity vector or vectors.",
            "Sum outlet momentum fluxes and subtract them from inlet momentum flux.",
            "Report fluid-on-plate force components, resultant, and direction.",
        ],
        "hand_calculation": ({} if hand_calculation is None else _plain(hand_calculation)),
        "ideal_comparison": ({} if ideal_comparison is None else _plain(ideal_comparison)),
        "parametric_study": _records(parametric_data, "Parametric data"),
        "discussion": selected_discussion,
        "conclusion": conclusion
        or (
            "The selected case was evaluated with the documented steady control-volume "
            "momentum model. Review the component directions, analytical checks, and "
            "parameter trends before drawing a case-specific engineering conclusion."
        ),
        "limitations": selected_limitations,
        "references": (
            "Placeholder - add only authoritative references personally checked by the student."
        ),
    }
    return cast(dict[str, Any], _plain(payload))


def _flatten(mapping: Mapping[str, Any], prefix: str = "") -> list[tuple[str, Any]]:
    rows: list[tuple[str, Any]] = []
    for key, value in mapping.items():
        name = f"{prefix}.{key}" if prefix else str(key)
        if isinstance(value, Mapping):
            rows.extend(_flatten(value, name))
        elif isinstance(value, list):
            rows.append((name, json.dumps(value, ensure_ascii=False, separators=(",", ":"))))
        else:
            rows.append((name, value))
    return rows


_LABELS = {
    "application_version": "Application version",
    "model_revision": "Model revision",
    "build_commit": "Build commit",
    "generated_at": "Generation timestamp",
    "density": "Fluid density",
    "dynamic_viscosity": "Dynamic viscosity",
    "diameter": "Jet diameter",
    "velocity": "Inlet jet velocity",
    "model": "Impact model",
    "plate_angle_deg": "Plate tangent angle",
    "outlet_angle_deg": "Outlet angle",
    "retention_coefficient": "Velocity retention coefficient",
    "split_fraction": "First outlet mass fraction",
    "fluid_preset": "Fluid preset",
    "unit_system": "Display unit preference",
    "area_m2": "Jet cross-sectional area",
    "flow_rate_m3_s": "Volumetric flow rate",
    "mass_flow_rate_kg_s": "Mass flow rate",
    "reynolds_number": "Reynolds number",
    "inlet_velocity_x_m_s": "Inlet velocity x-component",
    "inlet_velocity_y_m_s": "Inlet velocity y-component",
    "equivalent_outlet_velocity_x_m_s": "Equivalent outlet velocity x-component",
    "equivalent_outlet_velocity_y_m_s": "Equivalent outlet velocity y-component",
    "outlet_momentum_flux_x_n": "Outlet momentum flux x-component",
    "outlet_momentum_flux_y_n": "Outlet momentum flux y-component",
    "fx_n": "Horizontal reaction force",
    "fy_n": "Vertical reaction force",
    "resultant_force_n": "Resultant reaction force",
    "force_angle_deg": "Force direction angle",
    "force_direction_defined": "Force direction defined",
    "outlet_speed_m_s": "Outlet speed",
    "percentage_difference": "Percentage difference",
}


def _leaf_key(key: str) -> str:
    return key.rsplit(".", 1)[-1]


def _label(key: str) -> str:
    leaf = _leaf_key(key)
    return _LABELS.get(leaf, leaf.replace("_", " ").strip().title())


def unit_for_field(key: str) -> str:
    """Return the engineering unit associated with a serialized field name."""

    leaf = _leaf_key(key).lower()
    explicit = {
        "density": "kg/m^3",
        "dynamic_viscosity": "Pa s",
        "diameter": "m",
        "velocity": "m/s",
        "area_m2": "m^2",
        "flow_rate_m3_s": "m^3/s",
        "mass_flow_rate_kg_s": "kg/s",
        "reynolds_number": "dimensionless",
        "re": "dimensionless",
        "retention_coefficient": "dimensionless",
        "split_fraction": "dimensionless",
        "percentage_difference": "%",
    }
    if leaf in explicit:
        return explicit[leaf]
    if leaf.endswith("percentage_difference"):
        return "%"
    suffixes = (
        ("_m3_s", "m^3/s"),
        ("_kg_s", "kg/s"),
        ("_m_s", "m/s"),
        ("_m2", "m^2"),
        ("_deg", "deg"),
        ("_n", "N"),
    )
    for suffix, unit in suffixes:
        if leaf.endswith(suffix):
            return unit
    return ""


def _unit_for_value(key: str, value: Any) -> str:
    """Suppress a nominal unit when a presentation value is not applicable."""

    if value is None or value == "undefined":
        return ""
    unit = unit_for_field(key)
    if unit == "%" and (isinstance(value, bool) or not isinstance(value, (int, float))):
        return ""
    return unit


def _machine_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        return format(value, ".17g")
    return str(value)


def _display_value(value: Any) -> str:
    if value is None or value == "undefined":
        return "Not applicable"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, float):
        if value == 0:
            return "0"
        magnitude = abs(value)
        if magnitude < 1.0e-3 or magnitude >= 1.0e6:
            return f"{value:.6e}"
        return f"{value:.6g}"
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False, separators=(", ", ": "))
    return str(value)


def export_case_csv(
    inputs: Any,
    result: Any | None = None,
    **report_options: Any,
) -> bytes:
    """Return a long-form UTF-8 CSV for one traceable case."""

    payload = build_report_payload(inputs, result, **report_options)
    stream = io.StringIO(newline="")
    writer = csv.writer(stream, lineterminator="\n")
    writer.writerow(("section", "field", "quantity", "value", "unit"))
    sections = (
        ("report", payload["report"]),
        ("inputs", payload["case"]["inputs"]),
        ("results", payload["case"]["results"]),
    )
    for section, values in sections:
        for key, value in _flatten(values):
            writer.writerow(
                (section, key, _label(key), _machine_value(value), _unit_for_value(key, value))
            )
    return stream.getvalue().encode("utf-8")


def export_parametric_csv(table: Any) -> bytes:
    """Return a deterministic wide CSV for a parametric-study table."""

    rows = _records(table, "Parametric data")
    if not rows:
        raise ReportDataError("Parametric export data cannot be empty.")
    columns: list[str] = []
    for row in rows:
        for key in row:
            if key not in columns:
                columns.append(key)
    stream = io.StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=columns, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow({key: _machine_value(row.get(key)) for key in columns})
    return stream.getvalue().encode("utf-8")


def export_case_json(
    inputs: Any,
    result: Any | None = None,
    **report_options: Any,
) -> bytes:
    """Return standards-compliant, deterministic UTF-8 JSON for one case."""

    payload = build_report_payload(inputs, result, **report_options)
    try:
        text = json.dumps(
            payload,
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
            allow_nan=False,
        )
    except (TypeError, ValueError) as exc:
        raise ReportDataError(f"The case could not be serialized to JSON: {exc}") from exc
    return (text + "\n").encode("utf-8")


def _table_html(mapping: Mapping[str, Any], caption: str) -> str:
    rows = []
    for key, value in _flatten(mapping):
        rows.append(
            "<tr>"
            f'<th scope="row">{html.escape(_label(key))}</th>'
            f"<td>{html.escape(_display_value(value))}</td>"
            f"<td>{html.escape(_unit_for_value(key, value))}</td>"
            "</tr>"
        )
    return (
        '<div class="table-wrap"><table>'
        f"<caption>{html.escape(caption)}</caption>"
        '<thead><tr><th scope="col">Quantity</th><th scope="col">Value</th>'
        '<th scope="col">Unit</th></tr></thead><tbody>' + "".join(rows) + "</tbody></table></div>"
    )


def _value_from(mapping: Mapping[str, Any], *names: str, default: float = 0.0) -> float:
    for name in names:
        value = mapping.get(name)
        try:
            if value is not None:
                number = float(value)
                return number if math.isfinite(number) else default
        except (TypeError, ValueError):
            continue
    return default


def _arrow_svg(x1: float, y1: float, x2: float, y2: float, css_class: str) -> str:
    return (
        f'<line class="{css_class}" x1="{x1:.2f}" y1="{y1:.2f}" '
        f'x2="{x2:.2f}" y2="{y2:.2f}" marker-end="url(#arrow-{css_class})"/>'
    )


def _rectangle_exit_point(
    cx: float,
    cy: float,
    angle_deg: float,
    bounds: tuple[float, float, float, float],
    *,
    invert_y: bool,
    margin: float,
) -> tuple[float, float]:
    """Return a point just outside the first control-volume boundary crossed."""

    angle = math.radians(angle_deg)
    dx = math.cos(angle)
    dy = (-1.0 if invert_y else 1.0) * math.sin(angle)
    left, bottom_or_top, right, top_or_bottom = bounds
    distances: list[float] = []
    if dx > 0.0:
        distances.append((right - cx) / dx)
    elif dx < 0.0:
        distances.append((left - cx) / dx)
    if dy > 0.0:
        distances.append((top_or_bottom - cy) / dy)
    elif dy < 0.0:
        distances.append((bottom_or_top - cy) / dy)
    distance = min(item for item in distances if item >= 0.0) + margin
    return cx + distance * dx, cy + distance * dy


def _report_identity_rows(report: Mapping[str, Any]) -> list[tuple[str, Any]]:
    """Return the known academic identity fields supplied by the export UI."""

    rows: list[tuple[str, Any]] = []
    for field, label in _REPORT_IDENTITY_FIELDS:
        value = report.get(field)
        if value is not None and str(value).strip():
            rows.append((label, value))
    return rows


def _schematic_state(
    inputs: Mapping[str, Any], results: Mapping[str, Any], model: str
) -> tuple[float, float]:
    """Return model-consistent plate angle and normalized outlet speed."""

    if "normal" in model:
        plate_angle = 90.0
    elif "split" in model:
        plate_angle = _value_from(inputs, "plate_angle_deg", default=90.0)
    else:
        # The single-outlet and curved-vane constructions are prescribed by beta.
        plate_angle = _value_from(inputs, "outlet_angle_deg", default=90.0)
    inlet_speed = abs(_value_from(inputs, "velocity", default=0.0))
    outlet_speed = abs(_value_from(results, "outlet_speed_m_s", default=0.0))
    speed_ratio = 0.0 if inlet_speed <= 1.0e-12 else outlet_speed / inlet_speed
    return plate_angle, max(0.0, min(1.0, speed_ratio))


def build_schematic_svg(payload: Mapping[str, Any]) -> str:
    """Build a lightweight, model-consistent control-volume schematic."""

    case = payload.get("case", {})
    if not isinstance(case, Mapping):
        raise ReportDataError("The report payload has an invalid case structure.")
    inputs = case.get("inputs", {})
    results = case.get("results", {})
    if not isinstance(inputs, Mapping) or not isinstance(results, Mapping):
        raise ReportDataError("The report payload has an invalid case structure.")

    model = str(inputs.get("model", "normal_flat_plate")).lower()
    impact_x, impact_y = 400.0, 160.0
    plate_angle, outlet_speed_ratio = _schematic_state(inputs, results, model)
    tangent = math.radians(plate_angle)
    plate_dx = 72.0 * math.cos(tangent)
    plate_dy = -72.0 * math.sin(tangent)

    parts = [
        '<svg class="schematic" viewBox="0 0 720 320" role="img" '
        'aria-labelledby="schematic-title schematic-desc" xmlns="http://www.w3.org/2000/svg">',
        '<title id="schematic-title">Jet impact geometry and control volume</title>',
        '<desc id="schematic-desc">Incoming jet from left, plate or vane, prescribed outlet directions, coordinate axes, and force reaction.</desc>',
        "<defs>",
        '<marker id="arrow-flow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#118ab2"/></marker>',
        '<marker id="arrow-force" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#d1495b"/></marker>',
        '<marker id="arrow-axis" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#334155"/></marker>',
        "</defs>",
        '<rect x="275" y="65" width="250" height="190" rx="10" class="control-volume"/>',
        '<text x="285" y="88" class="cv-label">Control volume</text>',
        '<path d="M52 135 L112 135 L134 149 L134 171 L112 185 L52 185 Z" class="nozzle"/>',
        _arrow_svg(132, impact_y, impact_x - 8, impact_y, "flow"),
        '<text x="220" y="145" class="vector-label">V_in</text>',
    ]

    if "curved" in model:
        parts.append(
            f'<path d="M {impact_x + plate_dx:.2f} {impact_y + plate_dy:.2f} '
            f"Q {impact_x + 35:.2f} {impact_y:.2f} "
            f'{impact_x - plate_dx:.2f} {impact_y - plate_dy:.2f}" class="plate"/>'
        )
    else:
        parts.append(
            f'<line x1="{impact_x - plate_dx:.2f}" y1="{impact_y - plate_dy:.2f}" '
            f'x2="{impact_x + plate_dx:.2f}" y2="{impact_y + plate_dy:.2f}" class="plate"/>'
        )
    parts.append('<text x="430" y="190" class="vector-label">Plate / vane</text>')

    if outlet_speed_ratio <= 1.0e-12:
        parts.append('<text x="420" y="130" class="vector-label">V_out = 0</text>')
    elif "split" in model or "normal" in model:
        outlet_angle = plate_angle
        outlet_angles = (outlet_angle, outlet_angle + 180.0)
        split_fraction = (
            0.5 if "normal" in model else _value_from(inputs, "split_fraction", default=0.5)
        )
        fractions = (split_fraction, 1.0 - split_fraction)
        for index, (angle, fraction) in enumerate(zip(outlet_angles, fractions, strict=True), 1):
            if fraction <= 1.0e-12:
                continue
            x2, y2 = _rectangle_exit_point(
                impact_x,
                impact_y,
                angle,
                (275.0, 65.0, 525.0, 255.0),
                invert_y=True,
                margin=14.0,
            )
            parts.append(_arrow_svg(impact_x, impact_y, x2, y2, "flow"))
            fraction_label = f"; {fraction:.0%} mdot" if "split" in model else ""
            parts.append(
                f'<text x="{x2 + 8:.2f}" y="{y2:.2f}" class="vector-label">V_out,{index}{fraction_label}</text>'
            )
    else:
        outlet_angle = _value_from(inputs, "outlet_angle_deg", default=90.0)
        x2, y2 = _rectangle_exit_point(
            impact_x,
            impact_y,
            outlet_angle,
            (275.0, 65.0, 525.0, 255.0),
            invert_y=True,
            margin=14.0,
        )
        parts.append(_arrow_svg(impact_x, impact_y, x2, y2, "flow"))
        parts.append(f'<text x="{x2 + 8:.2f}" y="{y2:.2f}" class="vector-label">V_out</text>')

    fx = _value_from(results, "fx_n")
    fy = _value_from(results, "fy_n")
    force_mag = math.hypot(fx, fy)
    if force_mag > 0:
        x2 = impact_x + 86.0 * fx / force_mag
        y2 = impact_y - 86.0 * fy / force_mag
        parts.append(_arrow_svg(impact_x, impact_y, x2, y2, "force"))
        parts.append(f'<text x="{x2 + 8:.2f}" y="{y2 + 16:.2f}" class="force-label">F_R</text>')
    else:
        parts.append('<text x="420" y="184" class="force-label">F_R = 0</text>')

    parts.extend(
        [
            _arrow_svg(82, 267, 145, 267, "axis"),
            _arrow_svg(82, 267, 82, 210, "axis"),
            '<text x="151" y="273" class="axis-label">+x</text>',
            '<text x="65" y="205" class="axis-label">+y</text>',
            '<text x="275" y="293" class="note-label">Schematic - not to scale and not CFD</text>',
            "</svg>",
        ]
    )
    return "".join(parts)


def _figures_html(figures: Sequence[ReportFigure]) -> str:
    if not figures:
        return (
            '<p class="muted">No parametric-study image was supplied for this case export. '
            "Add a verified chart before final submission.</p>"
        )
    blocks = []
    for index, figure in enumerate(figures, 1):
        encoded = base64.b64encode(figure.image_bytes).decode("ascii")
        blocks.append(
            "<figure>"
            f"<h3>{html.escape(figure.title)}</h3>"
            f'<img src="data:{figure.mime_type};base64,{encoded}" '
            f'alt="{html.escape(figure.alt_text)}">'
            f"<figcaption>Figure {index}. {html.escape(figure.caption)}</figcaption>"
            "</figure>"
        )
    return "".join(blocks)


def _record_table_html(records: Sequence[Mapping[str, Any]], limit: int = 40) -> str:
    if not records:
        return '<p class="muted">No parametric-study table was supplied for this case export.</p>'
    columns: list[str] = []
    for row in records:
        for key in row:
            if key not in columns:
                columns.append(key)
    header = "".join(f'<th scope="col">{html.escape(str(key))}</th>' for key in columns)
    body = []
    for row in records[:limit]:
        body.append(
            "<tr>"
            + "".join(f"<td>{html.escape(_display_value(row.get(key)))}</td>" for key in columns)
            + "</tr>"
        )
    note = ""
    if len(records) > limit:
        note = f'<p class="muted">Showing the first {limit} of {len(records)} rows.</p>'
    return (
        '<div class="table-wrap"><table class="compact"><caption>Parametric-study data</caption><thead><tr>'
        + header
        + "</tr></thead><tbody>"
        + "".join(body)
        + "</tbody></table></div>"
        + note
    )


def _optional_mapping_html(value: Any, caption: str, empty_message: str) -> str:
    if not value:
        return f'<p class="muted">{html.escape(empty_message)}</p>'
    if isinstance(value, Mapping):
        return _table_html(value, caption)
    return f"<pre>{html.escape(json.dumps(value, ensure_ascii=False, indent=2))}</pre>"


def export_printable_html(
    inputs: Any,
    result: Any | None = None,
    *,
    figures: Sequence[ReportFigure] = (),
    **report_options: Any,
) -> bytes:
    """Return a self-contained, printable HTML engineering report."""

    payload = build_report_payload(inputs, result, **report_options)
    report = payload["report"]
    case = payload["case"]
    title = html.escape(str(report["title"]))
    subtitle = html.escape(str(report["subtitle"]))
    course = html.escape(str(report["course"]))
    identity_html = "".join(
        f"<br><strong>{html.escape(label)}:</strong> {html.escape(str(value))}"
        for label, value in _report_identity_rows(report)
    )
    assumptions = "".join(f"<li>{html.escape(str(item))}</li>" for item in payload["assumptions"])
    equations = "".join(
        f"<li><code>{html.escape(str(item))}</code></li>" for item in payload["governing_equations"]
    )
    procedure = "".join(
        f"<li>{html.escape(str(item))}</li>" for item in payload["calculation_procedure"]
    )
    discussion = "".join(f"<p>{html.escape(str(item))}</p>" for item in payload["discussion"])
    limitations = "".join(f"<li>{html.escape(str(item))}</li>" for item in payload["limitations"])
    course_report = report.get("interface_mode") == "Course Mode"
    ideal_section = ""
    if not course_report:
        ideal_section = (
            "<section><h2>9. Ideal and non-ideal percentage difference</h2>"
            + _optional_mapping_html(
                payload["ideal_comparison"],
                "Ideal/non-ideal comparison",
                "No ideal/non-ideal comparison was supplied for this report.",
            )
            + "</section>"
        )
    discussion_number = 9 if course_report else 10
    conclusion_number = discussion_number + 1
    limitations_number = discussion_number + 2
    references_number = discussion_number + 3
    stylesheet = """
    :root { color-scheme: light; --navy:#0b1f33; --blue:#0b6e99; --cyan:#1bb3d8;
      --red:#b4233b; --ink:#172033; --muted:#556275; --line:#cad5e1; --panel:#f4f8fb; }
    * { box-sizing: border-box; }
    body { margin:0; color:var(--ink); background:#fff; font-family:Arial,Helvetica,sans-serif;
      font-size:10.5pt; line-height:1.48; }
    main { max-width:900px; margin:0 auto; padding:32px 46px 56px; }
    .cover { min-height:88vh; display:flex; flex-direction:column; justify-content:center;
      border-top:12px solid var(--cyan); padding:44px 52px; background:linear-gradient(150deg,#f5fbff,#fff 65%); }
    .eyebrow { color:var(--blue); font-weight:700; letter-spacing:.09em; text-transform:uppercase; }
    h1 { color:var(--navy); font-size:31pt; line-height:1.12; margin:20px 0 14px; }
    h2 { color:var(--navy); font-size:18pt; border-bottom:2px solid var(--cyan);
      padding-bottom:7px; margin:34px 0 16px; }
    h3 { color:var(--blue); font-size:13pt; margin:20px 0 8px; }
    .subtitle { color:var(--blue); font-size:17pt; font-weight:600; }
    .meta { margin-top:42px; padding:18px 20px; background:var(--panel); border-left:5px solid var(--blue); }
    .notice { margin-top:20px; border:1px solid #f0b7c0; background:#fff6f7; padding:14px 16px; }
    .notice strong { color:#801b2c; }
    .muted { color:var(--muted); }
    .table-wrap { overflow-x:auto; margin:12px 0 20px; }
    table { width:100%; border-collapse:collapse; font-variant-numeric:tabular-nums; }
    table.compact { font-size:8pt; }
    caption { text-align:left; color:var(--navy); font-weight:700; padding:0 0 8px; }
    th, td { padding:7px 9px; border:1px solid var(--line); text-align:left; vertical-align:top; }
    thead th { color:#fff; background:var(--navy); }
    tbody th { width:48%; background:var(--panel); font-weight:600; }
    code, pre { font-family:"SFMono-Regular",Consolas,"Liberation Mono",monospace; }
    code { color:#073b55; }
    pre { white-space:pre-wrap; border:1px solid var(--line); background:var(--panel); padding:14px; }
    figure { margin:18px 0 24px; break-inside:avoid; }
    figure img { max-width:100%; height:auto; border:1px solid var(--line); }
    figcaption { margin-top:7px; color:var(--muted); font-size:9.5pt; }
    .schematic { width:100%; max-height:350px; background:#fbfdff; border:1px solid var(--line); }
    .control-volume { fill:none; stroke:#72849a; stroke-width:2; stroke-dasharray:8 6; }
    .nozzle { fill:#37485c; stroke:#172033; stroke-width:2; }
    .plate { fill:none; stroke:#172033; stroke-width:9; stroke-linecap:round; }
    .flow { stroke:#118ab2; stroke-width:8; stroke-linecap:round; }
    .force { stroke:#d1495b; stroke-width:5; stroke-linecap:round; }
    .axis { stroke:#334155; stroke-width:2.5; }
    text { font-family:Arial,Helvetica,sans-serif; fill:#172033; font-size:15px; }
    .force-label { fill:#a1162d; font-weight:700; }
    .cv-label,.note-label { fill:#556275; font-size:13px; }
    .axis-label { font-weight:700; }
    footer { margin-top:42px; border-top:1px solid var(--line); padding-top:12px; color:var(--muted); }
    @page { size:A4; margin:16mm 15mm 18mm; }
    @media print {
      main { max-width:none; padding:0; }
      .cover { min-height:250mm; break-after:page; }
      h2 { break-after:avoid; }
      table, .schematic, figure, pre { break-inside:avoid; }
      .table-wrap { overflow:visible; }
    }
    """
    document = f"""<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} - engineering report</title><style>{stylesheet}</style></head>
<body><main>
<header class="cover">
  <div class="eyebrow">{course}</div><h1>{title}</h1><div class="subtitle">{subtitle}</div>
  <div class="meta"><strong>Application version:</strong> {html.escape(str(report['application_version']))}<br>
  <strong>Model revision:</strong> {html.escape(str(report['model_revision']))}<br>
  <strong>Build commit:</strong> {html.escape(str(report['build_commit']))}<br>
  <strong>Generated:</strong> {html.escape(str(report['generated_at']))}<br>
  <strong>Analysis:</strong> Steady two-dimensional control-volume momentum<br>
  <strong>Primary result:</strong> Force exerted by the fluid on the plate{identity_html}</div>
  <div class="notice"><strong>Model scope.</strong> {html.escape(str(report['disclaimer']))}</div>
</header>
<section><h2>1. Input parameters</h2>{_table_html(case['inputs'], 'Current case inputs')}</section>
<section><h2>2. Geometry schematic and control volume</h2>{build_schematic_svg(payload)}
<p class="muted">Angles are measured counterclockwise from positive x. Arrow lengths are normalized for legibility.</p></section>
<section><h2>3. Assumptions</h2><ol>{assumptions}</ol></section>
<section><h2>4. Governing equations</h2><ul class="equations">{equations}</ul>
<p>The momentum equation gives force on the fluid. The report displays the equal-and-opposite force exerted by the fluid on the plate.</p></section>
<section><h2>5. Calculation procedure</h2><ol>{procedure}</ol></section>
<section><h2>6. Main results</h2>{_table_html(case['results'], 'Calculated SI results')}</section>
<section><h2>7. Parametric-study figures</h2>{_figures_html(figures)}
{_record_table_html(payload['parametric_study'])}</section>
<section><h2>8. Hand-calculation comparison</h2>
{_optional_mapping_html(payload['hand_calculation'], 'Hand calculation and simulator comparison', 'No hand-calculation data was supplied. Complete this section before final submission.')}</section>
{ideal_section}
<section><h2>{discussion_number}. Discussion</h2>{discussion}</section>
<section><h2>{conclusion_number}. Conclusion</h2><p>{html.escape(str(payload['conclusion']))}</p></section>
<section><h2>{limitations_number}. Limitations</h2><ul>{limitations}</ul></section>
<section><h2>{references_number}. References</h2><p>{html.escape(str(payload['references']))}</p></section>
<footer><strong>Student review required.</strong> {html.escape(str(report['review_note']))}</footer>
</main></body></html>"""
    return document.encode("utf-8")


def _presentation_velocity_chart_svg(velocity_study: Any) -> str:
    """Render supplied force-versus-velocity records as a compact inline SVG."""

    records = _records(velocity_study, "Presentation velocity study")
    if len(records) < 2:
        raise ReportDataError("The presentation summary requires at least two velocity-study rows.")

    series_names = ("Fx_N", "Fy_N", "FR_N")
    points: list[tuple[float, tuple[float, float, float]]] = []
    for row in records:
        try:
            velocity = float(row["velocity"])
            forces = cast(
                tuple[float, float, float], tuple(float(row[key]) for key in series_names)
            )
        except (KeyError, TypeError, ValueError) as exc:
            raise ReportDataError(
                "The presentation velocity study requires velocity, Fx_N, Fy_N, and FR_N columns."
            ) from exc
        if not all(math.isfinite(value) for value in (velocity, *forces)):
            raise ReportDataError("Presentation velocity-study values must be finite numbers.")
        points.append((velocity, forces))

    points.sort(key=lambda item: item[0])
    x_min, x_max = points[0][0], points[-1][0]
    if x_max <= x_min:
        raise ReportDataError("Presentation velocity-study values must span a nonzero range.")
    force_values = [value for _, forces in points for value in forces]
    y_min = min(0.0, *force_values)
    y_max = max(0.0, *force_values)
    if y_max == y_min:
        y_max = y_min + 1.0

    width, height = 620.0, 218.0
    left, right, top, bottom = 58.0, 18.0, 28.0, 38.0
    plot_width = width - left - right
    plot_height = height - top - bottom

    def x_position(value: float) -> float:
        return left + (value - x_min) * plot_width / (x_max - x_min)

    def y_position(value: float) -> float:
        return top + (y_max - value) * plot_height / (y_max - y_min)

    colors = ("#0891b2", "#d97706", "#e11d48")
    labels = ("Fx", "Fy", "FR")
    polylines = []
    legend = []
    for index, (color, label) in enumerate(zip(colors, labels, strict=True)):
        coordinates = " ".join(
            f"{x_position(velocity):.2f},{y_position(forces[index]):.2f}"
            for velocity, forces in points
        )
        polylines.append(
            f'<polyline points="{coordinates}" fill="none" stroke="{color}" '
            'stroke-width="2.6" vector-effect="non-scaling-stroke"/>'
        )
        legend_x = left + 355.0 + index * 62.0
        legend.append(
            f'<line x1="{legend_x:.1f}" y1="15" x2="{legend_x + 19:.1f}" y2="15" '
            f'stroke="{color}" stroke-width="3"/><text x="{legend_x + 24:.1f}" y="19">{label}</text>'
        )

    zero_y = y_position(0.0)
    return f"""<svg class="velocity-chart" viewBox="0 0 {width:g} {height:g}" role="img"
aria-label="Calculated Fx, Fy, and resultant force versus inlet velocity">
<text x="{left:g}" y="18" class="chart-title">Force versus inlet velocity</text>
<line x1="{left:g}" y1="{top:g}" x2="{left:g}" y2="{height - bottom:g}" class="chart-axis"/>
<line x1="{left:g}" y1="{zero_y:.2f}" x2="{width - right:g}" y2="{zero_y:.2f}" class="chart-zero"/>
<line x1="{left:g}" y1="{height - bottom:g}" x2="{width - right:g}" y2="{height - bottom:g}" class="chart-axis"/>
{''.join(polylines)}{''.join(legend)}
<text x="{left:g}" y="{height - 17:g}" text-anchor="middle">{x_min:.4g}</text>
<text x="{width - right:g}" y="{height - 17:g}" text-anchor="middle">{x_max:.4g}</text>
<text x="{left + plot_width / 2:.1f}" y="{height - 2:g}" text-anchor="middle">V (m/s)</text>
<text x="{left - 7:g}" y="{top + 4:g}" text-anchor="end">{y_max:.4g}</text>
<text x="{left - 7:g}" y="{height - bottom + 4:g}" text-anchor="end">{y_min:.4g}</text>
<text x="13" y="{top + plot_height / 2:.1f}" text-anchor="middle" transform="rotate(-90 13 {top + plot_height / 2:.1f})">Force (N)</text>
</svg>"""


def export_presentation_summary_html(
    inputs: Any,
    result: Any | None = None,
    *,
    velocity_study: Any,
    **report_options: Any,
) -> bytes:
    """Return a self-contained, single-page landscape presentation summary.

    The caller supplies the velocity-study table produced by the authoritative
    calculation layer.  This exporter only formats those values; it does not
    recompute force or momentum.
    """

    payload = build_report_payload(inputs, result, **report_options)
    report = payload["report"]
    case = payload["case"]
    results = case["results"]
    chart_svg = _presentation_velocity_chart_svg(velocity_study)
    primary_keys = ("fx_n", "fy_n", "resultant_force_n")
    flow_keys = ("area_m2", "flow_rate_m3_s", "mass_flow_rate_kg_s")
    try:
        primary = {key: results[key] for key in primary_keys}
        flow = {key: results[key] for key in flow_keys}
    except KeyError as exc:
        raise ReportDataError(
            "The presentation summary requires Fx, Fy, FR, area, flow-rate, and mass-flow results."
        ) from exc

    force_cards = "".join(
        '<div class="force-card">'
        f'<div class="symbol">{symbol}</div><div class="force-name">{name}</div>'
        f'<div class="force-value">{html.escape(_display_value(primary[key]))} N</div></div>'
        for key, symbol, name in (
            ("fx_n", "Fx", "Horizontal force"),
            ("fy_n", "Fy", "Vertical force"),
            ("resultant_force_n", "FR", "Resultant force"),
        )
    )

    def summary_text(value: Any, label: str, maximum: int) -> str:
        normalized = " ".join(str(value).split())
        if not normalized:
            raise ReportDataError(f"Presentation summary {label} cannot be blank.")
        if len(normalized) > maximum:
            raise ReportDataError(
                f"Presentation summary {label} must be at most {maximum} characters."
            )
        return normalized

    assumption_text = [
        summary_text(item, f"assumption {index}", 180)
        for index, item in enumerate(payload["assumptions"][:5], start=1)
    ]
    assumptions = "".join(f"<li>{html.escape(item)}</li>" for item in assumption_text)
    fx = html.escape(_display_value(primary["fx_n"]))
    fy = html.escape(_display_value(primary["fy_n"]))
    resultant = html.escape(_display_value(primary["resultant_force_n"]))
    interpretation = (
        f"For the active case, the fluid-on-plate reaction is Fx = {fx} N and Fy = {fy} N, "
        f"giving FR = {resultant} N. Component signs use +x with the inlet jet and +y upward."
    )
    identity = " · ".join(
        html.escape(summary_text(value, label.casefold(), 60))
        for label, value in _report_identity_rows(report)[:2]
        if value and "Complete before submission" not in str(value)
    )
    subtitle = html.escape(summary_text(report["subtitle"], "subtitle", 120))
    title = html.escape(summary_text(report["title"], "title", 120))
    raw_model = case["inputs"].get("model", "Selected impact model")
    model_label = report.get("model") or str(raw_model).replace("_", " ").title()
    model = html.escape(summary_text(model_label, "model label", 80))
    presentation_inputs = dict(case["inputs"])
    presentation_inputs["model"] = model_label
    if "fluid_preset" in presentation_inputs:
        presentation_inputs["fluid_preset"] = (
            str(presentation_inputs["fluid_preset"]).replace("_", " ").title()
        )
    if "unit_system" in presentation_inputs:
        presentation_inputs["unit_system"] = {
            "si": "SI",
            "us_customary": "US customary",
        }.get(
            str(presentation_inputs["unit_system"]),
            str(presentation_inputs["unit_system"]).replace("_", " ").title(),
        )
    stylesheet = """
    @page { size: A4 landscape; margin: 7mm; }
    * { box-sizing: border-box; }
    html, body { margin:0; padding:0; background:#fff; color:#172033;
      font-family:Arial,Helvetica,sans-serif; }
    .sheet { width:283mm; min-height:196mm; height:196mm;
      padding:5mm 6mm 4mm; border-top:3mm solid #0e7490; }
    header { display:flex; justify-content:space-between; gap:10mm; align-items:flex-start;
      border-bottom:1px solid #9fb7ca; padding-bottom:2.2mm; }
    h1 { margin:0; color:#0b1f33; font-size:19pt; line-height:1.08; }
    .subtitle { color:#0b6e99; font-size:9pt; font-weight:700; margin-top:1mm; }
    .trace { text-align:right; color:#556275; font-size:6.8pt; line-height:1.35; white-space:nowrap; }
    .grid { display:grid; grid-template-columns:42% 58%; gap:3.2mm; margin-top:3mm; }
    .panel { border:1px solid #cad5e1; border-radius:2mm; padding:2.4mm; background:#fbfdff;
      break-inside:avoid; }
    h2 { margin:0 0 1.5mm; color:#0b1f33; font-size:10pt; border-bottom:1px solid #1bb3d8;
      padding-bottom:1mm; }
    .force-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:2mm; margin-bottom:2.5mm; }
    .force-card { border-left:1.3mm solid #e11d48; background:#f4f8fb; padding:1.6mm 2mm; }
    .symbol { color:#0b6e99; font-weight:800; font-size:9pt; }
    .force-name { color:#556275; font-size:6.5pt; }
    .force-value { color:#0b1f33; font-size:12pt; font-weight:800; margin-top:.5mm; }
    .table-wrap { margin:0; overflow:hidden; }
    table { width:100%; border-collapse:collapse; font-size:6.7pt; line-height:1.12; }
    caption { text-align:left; font-weight:700; color:#0b1f33; padding:0 0 1mm; }
    th, td { border:1px solid #cad5e1; padding:.85mm 1.2mm; text-align:left; }
    thead th { color:#fff; background:#0b1f33; }
    tbody th { background:#f4f8fb; width:51%; font-weight:600; }
    .schematic-wrap { height:60mm; display:flex; align-items:center; justify-content:center; }
    .schematic-wrap svg { width:100%; height:100%; }
    .control-volume { fill:none; stroke:#72849a; stroke-width:2; stroke-dasharray:8 6; }
    .nozzle { fill:#37485c; stroke:#172033; stroke-width:2; }
    .plate { fill:none; stroke:#172033; stroke-width:9; stroke-linecap:round; }
    .flow { stroke:#118ab2; stroke-width:8; stroke-linecap:round; }
    .force { stroke:#d1495b; stroke-width:5; stroke-linecap:round; }
    .axis { stroke:#334155; stroke-width:2.5; }
    text { font-family:Arial,Helvetica,sans-serif; fill:#172033; font-size:12px; }
    .force-label { fill:#a1162d; font-weight:700; }
    .cv-label,.note-label { fill:#556275; font-size:11px; }
    .axis-label { font-weight:700; }
    .equation { margin:2mm 0; padding:1.7mm; background:#eaf5fa; color:#073b55;
      font:700 8.5pt "SFMono-Regular",Consolas,monospace; text-align:center; }
    .bottom { display:grid; grid-template-columns:38% 33% 29%; gap:3.2mm; margin-top:3mm; }
    .velocity-chart { width:100%; height:36mm; }
    .chart-axis { stroke:#334155; stroke-width:1.2; }
    .chart-zero { stroke:#94a3b8; stroke-width:1; stroke-dasharray:4 3; }
    .chart-title { font-weight:700; font-size:13px; fill:#0b1f33; }
    ul { margin:0; padding-left:4mm; font-size:6.7pt; line-height:1.23; }
    li { margin-bottom:.7mm; }
    p { margin:0 0 1.5mm; font-size:7pt; line-height:1.28; }
    .warning { border-left:1.2mm solid #b4233b; padding-left:2mm; color:#6f1627; font-weight:700; }
    footer { margin-top:2mm; padding-top:1.2mm; border-top:1px solid #cad5e1; color:#556275;
      font-size:6.3pt; display:flex; justify-content:space-between; }
    @media print { .sheet { break-after:avoid; break-inside:avoid; } }
    """
    document = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} - one-page presentation summary</title><style>{stylesheet}</style></head><body>
<main class="sheet"><header><div><h1>{title}</h1><div class="subtitle">{subtitle} · {model}</div></div>
<div class="trace">MEC350 Fluid Mechanics<br>Version {html.escape(str(report['application_version']))} · {html.escape(str(report['model_revision']))}<br>
Build {html.escape(str(report['build_commit']))} · {html.escape(str(report['generated_at']))}</div></header>
<div class="grid"><section class="panel"><h2>Active inputs and primary fluid-on-plate results</h2>
<div class="force-grid">{force_cards}</div>{_table_html(presentation_inputs, 'Active case inputs')}</section>
<section class="panel"><h2>Geometry and control volume</h2><div class="schematic-wrap">{build_schematic_svg(payload)}</div></section></div>
<div class="equation">F_plate = mdot V_in - sum(mdot_j V_out,j) &nbsp; | &nbsp; FR = sqrt(Fx^2 + Fy^2)</div>
<div class="bottom"><section class="panel"><h2>Flow quantities and velocity trend</h2>{_table_html(flow, 'Calculated SI flow quantities')}{chart_svg}</section>
<section class="panel"><h2>Model assumptions</h2><ul>{assumptions}</ul></section>
<section class="panel"><h2>Interpretation and limitation</h2><p>{interpretation}</p>
<p>The velocity chart holds density, diameter, geometry, angles, split, and prescribed retention coefficient fixed while V changes.</p>
<p class="warning">This application uses a numerical control-volume momentum model. The flow visualization is illustrative and is not a full CFD simulation. It is not experimental evidence.</p></section></div>
<footer><span>{identity or 'Student details: complete before submission'}</span><span>Force exerted by the fluid on the plate · +x inlet direction · +y upward</span></footer>
</main></body></html>"""
    return document.encode("utf-8")


def _ascii_pdf(value: Any) -> str:
    """Return Helvetica-safe report text and avoid missing-glyph squares."""

    text = str(value)
    substitutions = {
        "π": "pi",
        "ρ": "rho",
        "μ": "mu",
        "θ": "theta",
        "β": "beta",
        "°": " deg",
        "²": "^2",
        "³": "^3",
        "×": "x",
        "−": "-",
        "–": "-",
        "—": "-",
        "→": "->",
        "≤": "<=",
        "≥": ">=",
    }
    for source, replacement in substitutions.items():
        text = text.replace(source, replacement)
    return unicodedata.normalize("NFKD", text).encode("ascii", "replace").decode("ascii")


def _import_reportlab() -> dict[str, Any]:
    if not reportlab_available():
        raise ReportDependencyError(
            "Direct PDF export requires ReportLab. Install it with "
            "'python -m pip install reportlab', or use printable HTML."
        )
    try:
        shapes = importlib.import_module("reportlab.graphics.shapes")
        colors = importlib.import_module("reportlab.lib.colors")
        enums = importlib.import_module("reportlab.lib.enums")
        pagesizes = importlib.import_module("reportlab.lib.pagesizes")
        styles = importlib.import_module("reportlab.lib.styles")
        units = importlib.import_module("reportlab.lib.units")
        utils = importlib.import_module("reportlab.lib.utils")
        pdfmetrics = importlib.import_module("reportlab.pdfbase.pdfmetrics")
        platypus = importlib.import_module("reportlab.platypus")
    except ImportError as exc:
        raise ReportDependencyError(
            "ReportLab was found but could not be imported. Reinstall the project dependencies "
            "or use printable HTML."
        ) from exc
    return {
        "A4": pagesizes.A4,
        "BaseDocTemplate": platypus.BaseDocTemplate,
        "Drawing": shapes.Drawing,
        "Frame": platypus.Frame,
        "Image": platypus.Image,
        "ImageReader": utils.ImageReader,
        "KeepTogether": platypus.KeepTogether,
        "Line": shapes.Line,
        "PageBreak": platypus.PageBreak,
        "PageTemplate": platypus.PageTemplate,
        "Paragraph": platypus.Paragraph,
        "ParagraphStyle": styles.ParagraphStyle,
        "Polygon": shapes.Polygon,
        "Rect": shapes.Rect,
        "ShapePath": shapes.Path,
        "SimpleDocTemplate": platypus.SimpleDocTemplate,
        "SlowPageBreak": platypus.SlowPageBreak,
        "Spacer": platypus.Spacer,
        "String": shapes.String,
        "TA_LEFT": enums.TA_LEFT,
        "Table": platypus.Table,
        "TableStyle": platypus.TableStyle,
        "colors": colors,
        "getSampleStyleSheet": styles.getSampleStyleSheet,
        "mm": units.mm,
        "stringWidth": pdfmetrics.stringWidth,
    }


def _pdf_paragraph(value: Any, style: Any, paragraph_class: Any) -> Any:
    safe = html.escape(_ascii_pdf(value)).replace("\n", "<br/>")
    return paragraph_class(safe, style)


def _pdf_table(
    mapping: Mapping[str, Any],
    modules: Mapping[str, Any],
    styles: Mapping[str, Any],
) -> Any:
    Paragraph = modules["Paragraph"]
    data = [
        [
            _pdf_paragraph("Quantity", styles["TableHead"], Paragraph),
            _pdf_paragraph("Value", styles["TableHead"], Paragraph),
            _pdf_paragraph("Unit", styles["TableHead"], Paragraph),
        ]
    ]
    for key, value in _flatten(mapping):
        data.append(
            [
                _pdf_paragraph(_label(key), styles["TableCell"], Paragraph),
                _pdf_paragraph(_display_value(value), styles["TableCell"], Paragraph),
                _pdf_paragraph(_unit_for_value(key, value), styles["TableCell"], Paragraph),
            ]
        )
    table = modules["Table"](
        data, colWidths=[91 * modules["mm"], 55 * modules["mm"], 28 * modules["mm"]], repeatRows=1
    )
    table.setStyle(
        modules["TableStyle"](
            [
                ("BACKGROUND", (0, 0), (-1, 0), modules["colors"].HexColor("#0B1F33")),
                ("TEXTCOLOR", (0, 0), (-1, 0), modules["colors"].white),
                ("BACKGROUND", (0, 1), (0, -1), modules["colors"].HexColor("#F2F7FA")),
                ("GRID", (0, 0), (-1, -1), 0.45, modules["colors"].HexColor("#B7C4D1")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def _pdf_records_table(
    records: Sequence[Mapping[str, Any]],
    modules: Mapping[str, Any],
    styles: Mapping[str, Any],
    *,
    limit: int = 30,
) -> Any:
    """Create a compact, genuine tabular view of parameter-sweep records."""

    Paragraph = modules["Paragraph"]
    columns: list[str] = []
    for row in records:
        for key in row:
            if key not in columns:
                columns.append(str(key))
    if not columns:
        raise ReportDataError("Parametric records do not contain any columns.")
    # A portrait A4 report can carry the canonical eight sweep columns at this
    # compact width.  Preserve the swept parameter first and every engineering
    # metric returned by the calculation API.
    available_width = 174 * modules["mm"]
    weight_by_column = []
    for key in columns:
        lowered = key.lower()
        if lowered in {"re", "fx_n", "fy_n", "fr_n"}:
            weight_by_column.append(0.85)
        elif "flow" in lowered or "mdot" in lowered:
            weight_by_column.append(1.1)
        else:
            weight_by_column.append(1.0)
    weight_total = sum(weight_by_column)
    widths = [available_width * weight / weight_total for weight in weight_by_column]

    def header_text(key: str) -> str:
        compact = {
            "Fx_N": "Fx",
            "Fy_N": "Fy",
            "FR_N": "FR",
            "Q_m3_s": "Q",
            "mdot_kg_s": "mdot",
            "Re": "Re",
            "outlet_speed_m_s": "Outlet speed",
        }.get(key, _label(key))
        unit = unit_for_field(key)
        return f"{compact}\n[{unit}]" if unit else compact

    data = [[_pdf_paragraph(header_text(key), styles["CompactHead"], Paragraph) for key in columns]]
    for row in records[:limit]:
        data.append(
            [
                _pdf_paragraph(_display_value(row.get(key)), styles["CompactCell"], Paragraph)
                for key in columns
            ]
        )
    table = modules["Table"](data, colWidths=widths, repeatRows=1)
    table.setStyle(
        modules["TableStyle"](
            [
                ("BACKGROUND", (0, 0), (-1, 0), modules["colors"].HexColor("#0B1F33")),
                ("TEXTCOLOR", (0, 0), (-1, 0), modules["colors"].white),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [
                        modules["colors"].white,
                        modules["colors"].HexColor("#F2F7FA"),
                    ],
                ),
                ("GRID", (0, 0), (-1, -1), 0.35, modules["colors"].HexColor("#B7C4D1")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 3),
                ("RIGHTPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    return table


def _pdf_arrow(
    drawing: Any,
    modules: Mapping[str, Any],
    x1: float,
    y1: float,
    x2: float,
    y2: float,
    color: Any,
    width: float,
) -> None:
    drawing.add(modules["Line"](x1, y1, x2, y2, strokeColor=color, strokeWidth=width))
    angle = math.atan2(y2 - y1, x2 - x1)
    size = 7.0 + width
    left = (x2 - size * math.cos(angle - 0.45), y2 - size * math.sin(angle - 0.45))
    right = (x2 - size * math.cos(angle + 0.45), y2 - size * math.sin(angle + 0.45))
    drawing.add(
        modules["Polygon"](
            [x2, y2, left[0], left[1], right[0], right[1]],
            fillColor=color,
            strokeColor=color,
        )
    )


def _pdf_schematic(payload: Mapping[str, Any], modules: Mapping[str, Any]) -> Any:
    drawing = modules["Drawing"](500, 190)
    colors = modules["colors"]
    navy = colors.HexColor("#172033")
    blue = colors.HexColor("#118AB2")
    red = colors.HexColor("#D1495B")
    gray = colors.HexColor("#72849A")
    case = payload["case"]
    inputs = case["inputs"]
    results = case["results"]
    model = str(inputs.get("model", "normal_flat_plate")).lower()
    impact_x, impact_y = 285.0, 102.0
    drawing.add(
        modules["Rect"](
            205,
            29,
            185,
            150,
            rx=6,
            ry=6,
            fillColor=None,
            strokeColor=gray,
            strokeWidth=1.2,
            strokeDashArray=[5, 4],
        )
    )
    drawing.add(modules["String"](212, 164, "Control volume", fontSize=8, fillColor=gray))
    drawing.add(
        modules["Polygon"](
            [20, 83, 70, 83, 88, 94, 88, 110, 70, 121, 20, 121],
            fillColor=colors.HexColor("#37485C"),
            strokeColor=navy,
        )
    )
    _pdf_arrow(drawing, modules, 88, impact_y, impact_x - 6, impact_y, blue, 5)
    drawing.add(modules["String"](150, 111, "V_in", fontSize=9, fillColor=navy))

    plate_angle, outlet_speed_ratio = _schematic_state(inputs, results, model)
    tangent = math.radians(plate_angle)
    pdx, pdy = 52 * math.cos(tangent), 52 * math.sin(tangent)
    if "curved" in model:
        path = modules["ShapePath"]()
        path.moveTo(impact_x - pdx, impact_y - pdy)
        path.curveTo(
            impact_x + 25,
            impact_y - 20,
            impact_x + 25,
            impact_y + 20,
            impact_x + pdx,
            impact_y + pdy,
        )
        path.strokeColor = navy
        path.strokeWidth = 7
        path.fillColor = None
        drawing.add(path)
    else:
        drawing.add(
            modules["Line"](
                impact_x - pdx,
                impact_y - pdy,
                impact_x + pdx,
                impact_y + pdy,
                strokeColor=navy,
                strokeWidth=7,
            )
        )
    drawing.add(modules["String"](302, 146, "Plate / vane", fontSize=8, fillColor=navy))

    if outlet_speed_ratio <= 1.0e-12:
        drawing.add(modules["String"](300, 126, "V_out = 0", fontSize=8, fillColor=navy))
    elif "split" in model or "normal" in model:
        split_fraction = (
            0.5 if "normal" in model else _value_from(inputs, "split_fraction", default=0.5)
        )
        for index, (angle, fraction) in enumerate(
            zip(
                (plate_angle, plate_angle + 180), (split_fraction, 1 - split_fraction), strict=True
            ),
            1,
        ):
            if fraction <= 1.0e-12:
                continue
            x2, y2 = _rectangle_exit_point(
                impact_x,
                impact_y,
                angle,
                (205.0, 29.0, 390.0, 179.0),
                invert_y=False,
                margin=9.0,
            )
            _pdf_arrow(drawing, modules, impact_x, impact_y, x2, y2, blue, 4)
            label = f"V_out,{index}"
            if "split" in model:
                label += f"; {fraction:.0%} mdot"
            drawing.add(modules["String"](x2 + 4, y2, label, fontSize=8, fillColor=navy))
    else:
        angle = _value_from(inputs, "outlet_angle_deg", default=90.0)
        x2, y2 = _rectangle_exit_point(
            impact_x,
            impact_y,
            angle,
            (205.0, 29.0, 390.0, 179.0),
            invert_y=False,
            margin=9.0,
        )
        _pdf_arrow(drawing, modules, impact_x, impact_y, x2, y2, blue, 4)
        drawing.add(modules["String"](x2 + 4, y2, "V_out", fontSize=8, fillColor=navy))

    fx = _value_from(results, "fx_n")
    fy = _value_from(results, "fy_n")
    force_mag = math.hypot(fx, fy)
    if force_mag > 0:
        x2 = impact_x + 65 * fx / force_mag
        y2 = impact_y + 65 * fy / force_mag
        _pdf_arrow(drawing, modules, impact_x, impact_y, x2, y2, red, 3)
        drawing.add(modules["String"](x2 + 4, y2 - 10, "F_R", fontSize=9, fillColor=red))
    else:
        drawing.add(modules["String"](300, 90, "F_R = 0", fontSize=9, fillColor=red))

    _pdf_arrow(drawing, modules, 40, 30, 92, 30, navy, 1.4)
    _pdf_arrow(drawing, modules, 40, 30, 40, 75, navy, 1.4)
    drawing.add(modules["String"](97, 27, "+x", fontSize=8, fillColor=navy))
    drawing.add(modules["String"](28, 78, "+y", fontSize=8, fillColor=navy))
    drawing.add(
        modules["String"](
            190, 4, "Schematic - not to scale and not CFD", fontSize=8, fillColor=gray
        )
    )
    return drawing


def _pdf_figure(figure: ReportFigure, modules: Mapping[str, Any]) -> Any:
    try:
        reader = modules["ImageReader"](io.BytesIO(figure.image_bytes))
        width, height = reader.getSize()
    except Exception as exc:
        raise ReportDataError(f"Figure '{figure.title}' is not a readable raster image.") from exc
    max_width = 174 * modules["mm"]
    max_height = 108 * modules["mm"]
    scale = min(max_width / width, max_height / height, 1.0)
    return modules["Image"](
        io.BytesIO(figure.image_bytes), width=width * scale, height=height * scale
    )


def export_case_pdf(
    inputs: Any,
    result: Any | None = None,
    *,
    figures: Sequence[ReportFigure] = (),
    **report_options: Any,
) -> bytes:
    """Return a polished A4 PDF, or a readable dependency error.

    PDF generation is intentionally isolated behind an optional ReportLab
    import so the other three export formats continue to work without it.
    """

    payload = build_report_payload(inputs, result, **report_options)
    modules = _import_reportlab()
    colors = modules["colors"]
    styles = modules["getSampleStyleSheet"]()
    navy = colors.HexColor("#0B1F33")
    blue = colors.HexColor("#0B6E99")
    cyan = colors.HexColor("#1BB3D8")
    muted = colors.HexColor("#556275")
    panel = colors.HexColor("#F2F7FA")
    styles.add(
        modules["ParagraphStyle"](
            "CoverTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=25,
            leading=30,
            textColor=navy,
            alignment=modules["TA_LEFT"],
            spaceAfter=15,
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "CoverSubtitle",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=15,
            leading=19,
            textColor=blue,
            spaceAfter=22,
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "Section",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=15,
            leading=19,
            textColor=navy,
            spaceBefore=12,
            spaceAfter=9,
            borderColor=cyan,
            borderWidth=0,
            borderPadding=(0, 0, 4, 0),
            keepWithNext=1,
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "Subsection",
            parent=styles["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=blue,
            spaceBefore=9,
            spaceAfter=5,
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "ReportBody",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13.5,
            textColor=colors.HexColor("#172033"),
            spaceAfter=7,
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "BulletBody",
            parent=styles["ReportBody"],
            leftIndent=13,
            firstLineIndent=-7,
            bulletIndent=0,
            spaceAfter=3,
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "Equation",
            parent=styles["ReportBody"],
            fontName="Courier",
            fontSize=9,
            leading=12,
            leftIndent=14,
            textColor=colors.HexColor("#073B55"),
            backColor=panel,
            borderPadding=6,
            spaceAfter=5,
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "TableHead",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=10,
            textColor=colors.white,
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "TableCell",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=8.2,
            leading=10.2,
            textColor=colors.HexColor("#172033"),
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "CompactHead",
            parent=styles["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=6.2,
            leading=7.2,
            textColor=colors.white,
            alignment=modules["TA_LEFT"],
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "CompactCell",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=6.2,
            leading=7.4,
            textColor=colors.HexColor("#172033"),
        )
    )
    styles.add(
        modules["ParagraphStyle"](
            "SmallMuted",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=8,
            leading=10.5,
            textColor=muted,
            spaceAfter=6,
        )
    )

    buffer = io.BytesIO()
    document = modules["BaseDocTemplate"](
        buffer,
        pagesize=modules["A4"],
        leftMargin=18 * modules["mm"],
        rightMargin=18 * modules["mm"],
        topMargin=20 * modules["mm"],
        bottomMargin=18 * modules["mm"],
        title=_ascii_pdf(payload["report"]["title"]),
        author="JetForce Studio",
        subject="MEC350 control-volume momentum analysis",
    )
    story: list[Any] = []
    Paragraph = modules["Paragraph"]
    Spacer = modules["Spacer"]

    story.append(Spacer(1, 29 * modules["mm"]))
    story.append(_pdf_paragraph(payload["report"]["course"], styles["Subsection"], Paragraph))
    story.append(_pdf_paragraph(payload["report"]["title"], styles["CoverTitle"], Paragraph))
    story.append(_pdf_paragraph(payload["report"]["subtitle"], styles["CoverSubtitle"], Paragraph))
    cover_data = [
        ["Application version", payload["report"]["application_version"]],
        ["Model revision", payload["report"]["model_revision"]],
        ["Build commit", payload["report"]["build_commit"]],
        ["Generated", payload["report"]["generated_at"]],
        ["Analysis", "Steady two-dimensional control-volume momentum"],
        ["Primary result", "Force exerted by the fluid on the plate"],
    ]
    cover_data.extend([label, value] for label, value in _report_identity_rows(payload["report"]))
    cover_table = modules["Table"](
        [
            [
                _pdf_paragraph(a, styles["TableCell"], Paragraph),
                _pdf_paragraph(b, styles["TableCell"], Paragraph),
            ]
            for a, b in cover_data
        ],
        colWidths=[40 * modules["mm"], 120 * modules["mm"]],
    )
    cover_table.setStyle(
        modules["TableStyle"](
            [
                ("BACKGROUND", (0, 0), (-1, -1), panel),
                ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#CAD5E1")),
                ("LINEBEFORE", (0, 0), (0, -1), 4, blue),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 7),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]
        )
    )
    story.append(cover_table)
    story.append(Spacer(1, 8 * modules["mm"]))
    story.append(_pdf_paragraph(payload["report"]["disclaimer"], styles["ReportBody"], Paragraph))
    story.append(_pdf_paragraph(payload["report"]["review_note"], styles["SmallMuted"], Paragraph))
    story.append(modules["SlowPageBreak"]())

    def heading(text: str) -> None:
        story.append(_pdf_paragraph(text, styles["Section"], Paragraph))

    def body(text: Any, style: str = "ReportBody") -> None:
        story.append(_pdf_paragraph(text, styles[style], Paragraph))

    heading("1. Input parameters")
    story.append(_pdf_table(payload["case"]["inputs"], modules, styles))
    heading("2. Geometry schematic and control volume")
    story.append(_pdf_schematic(payload, modules))
    body(
        "Angles are measured counterclockwise from positive x. Arrow lengths are normalized for legibility.",
        "SmallMuted",
    )
    heading("3. Assumptions")
    for item in payload["assumptions"]:
        body(f"- {item}", "BulletBody")
    heading("4. Governing equations")
    for equation in payload["governing_equations"]:
        body(equation, "Equation")
    body(
        "The momentum equation gives force on the fluid. The report displays the equal-and-opposite force exerted by the fluid on the plate."
    )
    heading("5. Calculation procedure")
    for index, item in enumerate(payload["calculation_procedure"], 1):
        body(f"{index}. {item}", "BulletBody")
    heading("6. Main results")
    story.append(_pdf_table(payload["case"]["results"], modules, styles))

    heading("7. Parametric-study figures")
    if figures:
        for index, figure in enumerate(figures, 1):
            if index > 1:
                story.append(modules["SlowPageBreak"]())
            story.append(
                modules["KeepTogether"](
                    [
                        _pdf_paragraph(figure.title, styles["Subsection"], Paragraph),
                        _pdf_figure(figure, modules),
                        _pdf_paragraph(
                            f"Figure {index}. {figure.caption}", styles["SmallMuted"], Paragraph
                        ),
                    ]
                )
            )
    else:
        body(
            "No parametric-study image was supplied for this case export. Add a verified chart before final submission.",
            "SmallMuted",
        )
    records = payload["parametric_study"]
    if records:
        # Reserve space for the excerpt label as well as the verified figure.
        # Seven rows prevent the excerpt label or a single trailing table row
        # from being orphaned on an otherwise blank portrait A4 page.
        row_limit = 7 if figures else 11
        first_rows = records[:row_limit]
        if len(records) > len(first_rows):
            body(
                f"Table excerpt: first {len(first_rows)} of {len(records)} parametric rows.",
                "SmallMuted",
            )
        story.append(_pdf_records_table(first_rows, modules, styles))
    else:
        body("No parametric-study table was supplied for this case export.", "SmallMuted")

    story.append(modules["SlowPageBreak"]())
    heading("8. Hand-calculation comparison")
    if payload["hand_calculation"]:
        if isinstance(payload["hand_calculation"], Mapping):
            story.append(_pdf_table(payload["hand_calculation"], modules, styles))
        else:
            body(json.dumps(payload["hand_calculation"], ensure_ascii=True, indent=2))
    else:
        body(
            "No hand-calculation data was supplied. Complete this section before final submission.",
            "SmallMuted",
        )

    course_report = payload["report"].get("interface_mode") == "Course Mode"
    if not course_report:
        heading("9. Ideal and non-ideal percentage difference")
        if payload["ideal_comparison"]:
            if isinstance(payload["ideal_comparison"], Mapping):
                story.append(_pdf_table(payload["ideal_comparison"], modules, styles))
            else:
                body(json.dumps(payload["ideal_comparison"], ensure_ascii=True, indent=2))
        else:
            body("No ideal/non-ideal comparison was supplied for this report.", "SmallMuted")

    discussion_items = list(payload["discussion"])
    discussion_number = 9 if course_report else 10
    discussion_intro = [
        _pdf_paragraph(f"{discussion_number}. Discussion", styles["Section"], Paragraph)
    ]
    if discussion_items:
        discussion_intro.append(
            _pdf_paragraph(discussion_items[0], styles["ReportBody"], Paragraph)
        )
    story.append(modules["KeepTogether"](discussion_intro))
    for item in discussion_items[1:]:
        body(item)
    story.append(
        modules["KeepTogether"](
            [
                _pdf_paragraph(
                    f"{discussion_number + 1}. Conclusion", styles["Section"], Paragraph
                ),
                _pdf_paragraph(payload["conclusion"], styles["ReportBody"], Paragraph),
            ]
        )
    )
    limitation_items = list(payload["limitations"])
    limitation_intro = [
        _pdf_paragraph(f"{discussion_number + 2}. Limitations", styles["Section"], Paragraph)
    ]
    if limitation_items:
        limitation_intro.append(
            _pdf_paragraph(f"- {limitation_items[0]}", styles["BulletBody"], Paragraph)
        )
    story.append(modules["KeepTogether"](limitation_intro))
    for item in limitation_items[1:]:
        body(f"- {item}", "BulletBody")
    story.append(
        modules["KeepTogether"](
            [
                _pdf_paragraph(
                    f"{discussion_number + 3}. References", styles["Section"], Paragraph
                ),
                _pdf_paragraph(payload["references"], styles["ReportBody"], Paragraph),
                modules["Spacer"](1, 5 * modules["mm"]),
                _pdf_paragraph(
                    f"Student review required. {payload['report']['review_note']}",
                    styles["SmallMuted"],
                    Paragraph,
                ),
            ]
        )
    )

    def decorate_page(canvas: Any, doc: Any) -> None:
        canvas.saveState()
        width, height = modules["A4"]
        if doc.page > 1:
            canvas.setStrokeColor(cyan)
            canvas.setLineWidth(1.1)
            canvas.line(
                18 * modules["mm"],
                height - 14 * modules["mm"],
                width - 18 * modules["mm"],
                height - 14 * modules["mm"],
            )
            canvas.setFillColor(muted)
            canvas.setFont("Helvetica", 7.5)
            canvas.drawString(
                18 * modules["mm"], height - 11 * modules["mm"], "JetForce Studio - MEC350"
            )
        footer = f"Page {doc.page} | Control-volume momentum model - not CFD"
        canvas.setFillColor(muted)
        canvas.setFont("Helvetica", 7.5)
        text_width = modules["stringWidth"](footer, "Helvetica", 7.5)
        canvas.drawString((width - text_width) / 2, 9 * modules["mm"], footer)
        canvas.restoreState()

    try:
        frame = modules["Frame"](
            document.leftMargin,
            document.bottomMargin,
            document.width,
            document.height,
            id="report-body",
        )
        document.addPageTemplates(
            [
                modules["PageTemplate"](
                    id="report",
                    frames=[frame],
                    onPage=decorate_page,
                    pagesize=modules["A4"],
                )
            ]
        )
        document.build(story)
    except ReportError:
        raise
    except Exception as exc:
        raise ReportError(
            "PDF generation failed. Verify supplied figures or use printable HTML."
        ) from exc
    pdf_bytes = buffer.getvalue()
    if not pdf_bytes.startswith(b"%PDF-") or len(pdf_bytes) < 1000:
        raise ReportError("PDF generation did not produce a valid document.")
    return pdf_bytes


def safe_export_filename(
    stem: str = "jetforce_case",
    extension: str = "json",
    *,
    generated_at: datetime | None = None,
) -> str:
    """Return a path-free export filename with a sortable UTC timestamp."""

    clean_stem = re.sub(r"[^A-Za-z0-9_-]+", "_", stem.strip()).strip("_-")
    clean_extension = re.sub(r"[^A-Za-z0-9]+", "", extension.lstrip("."))
    if not clean_stem:
        clean_stem = "jetforce_case"
    if not clean_extension:
        raise ReportDataError("Export extension must contain letters or numbers.")
    instant = generated_at or datetime.now(UTC)
    if instant.tzinfo is None:
        instant = instant.replace(tzinfo=UTC)
    stamp = instant.astimezone(UTC).strftime("%Y%m%dT%H%M%SZ")
    return f"{clean_stem}_{stamp}.{clean_extension.lower()}"


def write_export_file(data: bytes | str, destination: str | Path) -> Path:
    """Atomically write one generated export to an existing directory."""

    target = Path(destination).expanduser()
    if not target.name:
        raise ReportWriteError("An export filename is required.")
    if not target.parent.exists():
        raise ReportWriteError(f"Export directory does not exist: {target.parent}")
    payload = data.encode("utf-8") if isinstance(data, str) else data
    if not payload:
        raise ReportDataError("Generated export data cannot be empty.")
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb", prefix=f".{target.name}.", suffix=".tmp", dir=target.parent, delete=False
        ) as stream:
            temporary_name = stream.name
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_name, target)
    except OSError as exc:
        if temporary_name is not None:
            with contextlib.suppress(OSError):
                Path(temporary_name).unlink(missing_ok=True)
        raise ReportWriteError(f"Could not write export file '{target}': {exc}") from exc
    return target


# Compatibility aliases with descriptive names for Streamlit pages and notebooks.
generate_csv = export_case_csv
generate_json = export_case_json
generate_html_report = export_printable_html
generate_presentation_summary = export_presentation_summary_html
generate_pdf_report = export_case_pdf
dataframe_to_csv = export_parametric_csv
save_export = write_export_file


__all__ = [
    "DEFAULT_ASSUMPTIONS",
    "DISCLAIMER",
    "GOVERNING_EQUATIONS",
    "REVIEW_NOTE",
    "ReportDataError",
    "ReportDependencyError",
    "ReportError",
    "ReportFigure",
    "ReportWriteError",
    "build_report_payload",
    "build_schematic_svg",
    "dataframe_to_csv",
    "export_case_csv",
    "export_case_json",
    "export_case_pdf",
    "export_parametric_csv",
    "export_presentation_summary_html",
    "export_printable_html",
    "generate_csv",
    "generate_html_report",
    "generate_json",
    "generate_pdf_report",
    "generate_presentation_summary",
    "reportlab_available",
    "safe_export_filename",
    "save_export",
    "unit_for_field",
    "write_export_file",
]
